version: 2
jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.2-node
        environment:
          RAILS_ENV: test
    working_directory: ~/self-metrics
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            gem update bundler
            bundle config set --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
  publish:
    docker:
      - image: cimg/ruby:3.1.2-node
    working_directory: ~/self-metrics
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker login
          command: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
      - run:
          name: Build image
          command: docker build -t ghcr.io/$GHCR_USERNAME/self-metrics:latest .
      - run:
          name: Push image
          command: docker push ghcr.io/$GHCR_USERNAME/self-metrics:latest
workflows:
  version: 2
  test-and-publish:
    jobs:
      - test
      - publish:
          requires:
            - test