# Generated by Django 2.0.7 on 2018-10-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sleep', models.DateTimeField()),
                ('end_sleep', models.DateTimeField()),
            ],
        ),
    ]
