# Generated by Django 2.0.7 on 2018-10-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sleep',
            old_name='end_sleep',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='start_sleep',
            new_name='start',
        ),
    ]
